config/routes.rb
Vgscorecard::Application.routes.draw do
  devise_for :users

  root :to => "courses#index"
  match "/admin" => "admin/courses#index"
  
  resources :courses, only: [:index, :show] do 
    get "all"
  end
  
  resources :users, only: [:index, :show]
  
  resources :scorecards
  
  namespace :admin do 
    resources :courses
    resources :users
  end
end

app/models/scorecard.rb
class Scorecard < ActiveRecord::Base
  attr_accessible :course_id, :played_on
  
  has_many :user_scores, dependent: :destroy
  has_many :users, through: :user_scores
  belongs_to :course
  accepts_nested_attributes_for :user_scores, reject_if: lambda { |a| a[:user_id].blank? }
  attr_accessible :user_scores_attributes
  
  validates :played_on, :course_id, presence: true
  
  def top_score
    top = self.user_scores.first
    self.user_scores.each do |u|
      if u.total > top.total
        top = u
      end
    end
    top.total
  end
  
  def top_player
    top = self.user_scores.first
    self.user_scores.each do |u|
      if u.total < top.total
        top = u
      end
    end
    top.user    
  end

end

app/controllers/scorecards_controller.rb
class ScorecardsController < ApplicationController
  before_filter :authenticate_user!
  def show
    @scorecard = Scorecard.find(params[:id])
  end
  
  def new
    @scorecard = Scorecard.new
    @users = User.where("role = ?", "golfer")
    @course = Course.find(params[:course])
    
    holes = @course.holes.count
    
    4.times do 
      user_score = @scorecard.user_scores.build
      holes.times do 
        user_score.scores.build
      end
    end  
  end
  
  def create
    @scorecard = Scorecard.new(params[:scorecard])
    @course = Course.find(@scorecard.course_id)
    
    if @scorecard.save
      redirect_to course_path(@course), notice: "Course successfully created."
    else
      @users = User.all
      render :new
    end    
  end
  
  def edit
    @scorecard = Scorecard.where("id = ?", params[:id]).first
    @users = User.where("role = ?", "golfer")
    @course = @scorecard.course   
  end
  
  def update
    @scorecard = Scorecard.where("id = ?", params[:id]).first
    @course = Course.find(@scorecard.course_id)
    
    if @scorecard.update_attributes(params[:scorecard])
      redirect_to scorecard_path(@scorecard), notice: "Scorecard succcessfully updated."
    else
      @users = User.all
      render :edit
    end
  end
end

app/views/scorecards/_form.html.erb
<div class="large-12 columns">
  <%= f.input :course_id, as: :hidden, input_html: { value: @course.id }%>
  <%= f.input :played_on, as: :string %>
  <table>
    <thead>
      <tr>
        <th style="width:30px">Hole<br />Par</br />Yards</th>
        <% @course.holes.each do |h| %>
          <th align="center"><%= h.hole_number %><br /><%= h.par %><br /><%= h.yards %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <%= f.fields_for :user_scores do |builder| %>
        <%= render "user_score_fields", f: builder %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/scorecards/_score_fields.html.erb
<td>
  <% hole = Hole.where("course_id = ? and hole_number = ?", @course.id, i).first %>
  <%= f.input :score %>
  <%= f.input :hole_id, as: :hidden, input_html: { value: hole.id }%>
</td>

app/views/scorecards/_user_score_fields.html.erb
<tr>
  <td>
    <% unless @users.empty? %>
      <%= f.input :user_id, collection: @users, prompt: "Select a user" %>
    <% end %>
  </td>
  <% i = 1 %>
  <%= f.fields_for :scores do |builder| %>
    <%= render partial: "score_fields", locals: { f: builder, i: i } %>
    <% i = i+1 %>
  <% end %>
</tr>

app/views/scorecards/edit.html.erb
<div class="row push-up">
	<div class="large-12 columns">
		<div class="bg pad">
		  <h1><%= @course.name %></h1>
			<%= simple_form_for @scorecard, html: { class: "large-8" } do |f| %>
				<%= render partial: 'form', locals: { f: f } %>
				<div class="large-12 columns">
				  <%= link_to "Cancel", course_path(@course), class: "radius button alert" %>
				  <%= f.button :submit, "Update", class: "radius button" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/scorecards/new.html.erb
<div class="row push-up">
	<div class="large-12 columns">
		<div class="bg pad">
		  <h1><%= @course.name %></h1>
			<%= simple_form_for @scorecard, html: { class: "large-8" } do |f| %>
				<%= render partial: 'form', locals: { f: f } %>
				<div class="large-12 columns">
				  <%= link_to "Cancel", course_path(@course), class: "radius button alert" %>
				  <%= f.button :submit, "Create", class: "radius button" %>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/scorecards/show.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1><%= @scorecard.course.name %> <small><%= @scorecard.played_on %></small></h1>
  </div>
  <div class="large-12 columns">
    <table>
      <thead>
        <tr>
          <th></th>
          <th style="width:30px">Hole<br />Par</br />Yards</th>
          <% @scorecard.course.holes.each do |h| %>
            <th align="center"><%= h.hole_number %><br /><%= h.par %><br /><%= h.yards %></th>
          <% end %>
          <th>Total<br /><%= @scorecard.course.par %><br /><%= @scorecard.course.total_yards %></th>
        </tr>
      </thead>
      <tbody>
        <% @scorecard.user_scores.each do |u| %>
        <tr>
          <td>
            <% if u.user == @scorecard.top_player %>
              <%= image_tag("crown.png", size: "22x22") %>
            <% end %>            
          </td>
          <td>
            <%= u.user.name %>
          </td>
          <% u.scores.order("hole_id ASC").each do |s| %>
            <td><div class="<%= s.rank %>"><%= s.score %></div></td>
          <% end %>
          <td><%= u.total %></td>
        </tr>
        <% end %>    
      </tbody>
    </table>
    <%= link_to "Back", course_path(@scorecard.course), class: "radius button" %>
    <%= link_to "Edit", edit_scorecard_path(@scorecard), class: "radius button" if @scorecard.users.include?(current_user) %>
  </div>
  <% @scorecard.user_scores.each do |u| %>
  <div class="large-<%= 12/@scorecard.user_scores.count %> columns">
    <div class="panel">
      <h4><%= u.user.name %></h4>
      <div class="subheader">
        Hole-in-Ones: <%= u.hole_in_ones %><br />
        Albatrosses: <%= u.albatrosses %><br />
        Eagles: <%= u.eagles %><br />
        Birdies: <%= u.birdies %><br />
        Evens: <%= u.evens %><br />
        Bogeys: <%= u.bogeys %><br />
        Double Bogeys: <%= u.double_bogeys %><br />
        +Bogeys: <%= u.more_bogeys %>
      </div>
    </div>
  </div>
  <% end %>
</div>