config/routes.rb
Vgscorecard::Application.routes.draw do
  devise_for :users

  root :to => "courses#index"
  match "/admin" => "admin/courses#index"
  
  resources :courses, only: [:index, :show] do 
    get "all"
  end
  
  resources :users, only: [:index, :show]
  
  resources :scorecards
  
  namespace :admin do 
    resources :courses
    resources :users
  end
end

app/controllers/admin/courses_controller.rb
class Admin::CoursesController < ApplicationController
  before_filter :authenticate_user!
  def index
    if current_user.role == 'admin'
      @courses = Course.all
    else
      redirect_to courses_path
    end
  end
  
  def new
    if current_user.role == 'admin'
      @course = Course.new
      @course_types = CourseType.all
      18.times do 
        @course.holes.build
      end
    else
      redirect_to courses_path
    end
  end
  
  def create
    @course = Course.new(params[:course])
    
    if @course.save
      redirect_to admin_courses_path, notice: "Course successfully created."
    else
      @course_types = CourseType.all
      render :new
    end
  end
  
  def edit
    if current_user.role == 'admin'    
      @course = Course.find(params[:id])
      @course_types = CourseType.all
    else
      redirect_to courses_path
    end
  end
  
  def update
    @course = Course.find(params[:id])
    if @course.update_attributes(params[:course])
      redirect_to admin_courses_path, notice: "Course successfully edited."
    else
      @course_types = CourseType.all
      render :edit
    end
  end
  
  def destroy
    
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    if params[:type]
      course_type = CourseType.where("name = ?", params[:type]).first
      @courses = Course.where("course_type_id = ?", course_type)
    else
      @courses = Course.order("name ASC").all
    end
    @count = Course.all.count
    @json = @courses.to_gmaps4rails
  end
  
  def show
    @course = Course.find(params[:id])
    @gmaps_options = {
      "map_options" => {
        "auto_zoom" => false,
        "zoom" => 12,
        "center_latitude" => @course.latitude,
        "center_longitude" => @course.longitude,
        "container_class" => "gmaps4rails_map_single"
      },
      "markers" => {
        "data" => @course.to_gmaps4rails,
        "options" => {
          "picture" =>  "/assets/golfing.png",
          "width" => "32",
          "height" => "32"
        }
      }
    }
  end
  
  def all
    @course = Course.find(params[:course_id])
  end
end

app/views/courses/all.html.erb
<div class="row">
  <div class="large-12 columns">
    <h1><%= @course.name %></h1>
    <ul class="no-disc">
      <% @course.scorecards.order("played_on DESC").each do |sc| %>
        <li><%= link_to sc.played_on, scorecard_path(sc) %> - 
        <% sc.user_scores.each do |u| %>
          <%= link_to u.user.name, user_path(u.user) %> (<%= u.total %>)
        <% end %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/courses/index.html.erb
<div class="row">
    <div class="large-12 columns"><h1>Courses
      <small>
        <dl class="sub-nav">
  			  <dt>Filter:</dt>
  			  <dd class="<%= active(courses_path(all: true)) %>"><%= link_to "All (#{@count})", courses_path(all: true) %></dd>
  			  <dd class="<%= active(courses_path(type: "Full")) %>"><%= link_to "Full", courses_path(type: "Full") %></dd>
  				<dd class="<%= active(courses_path(type: "Par 3")) %>"><%= link_to "Par 3", courses_path(type: "Par 3") %></dd>
  				<dd class="<%= active(courses_path(type: "Executive")) %>"><%= link_to "Executive", courses_path(type: "Executive") %></dd>
  			</dl>
  		</small>
      </h1></div>

    <div class="large-12 columns">
      <% if @courses.count == 0 %>
        <div class="large-12 columns">
          <p>There are no courses entered.</p>
        </div>      
      <% else %>    
      <ul class="no-disc"> 
      <% @courses.each do |c| %>
        <li><%= link_to c.name, course_path(c) %> - <%= c.city %>, <%= c.province %> (<%= c.course_type.name %>) 
          <%= " - <em>Last Played: #{c.scorecards.last.played_on}</em>".html_safe if c.scorecards.count > 0 %>
        </li>
      <% end %>
      </ul>
      <% end %>
    </div>
    
    <div class="large-12 columns">
      <div class="gmaps4rails_map"><%= gmaps4rails(@json) %></div>
    </div>
</div>

app/views/courses/show.html.erb
<% content_for :title, "#{@course.name}, #{@course.city.strip}, #{@course.province.strip} — Vangolfers" %>
<div class="row">
  <div class="large-6 columns">
    <h2><%= @course.name %></h2>
      <div class="subheader"><%= @course.address %><br />
        <%= "#{@course.city}, #{@course.province}" %><br />
        <%= "#{@course.country}, #{@course.postal}" %><br />
        <br />
        <%= @course.phone %>
      </div>  
  </div>
  <div class="large-3 columns subheader">
    <%= @course.course_type.name %> - <%= @course.par %><br />
    <%= pluralize(@course.holes.count, "hole")%><br />
    <%= @course.total_yards %> yards<br />
    Front 9: <%= @course.front_9_yards %> yards (par <%= @course.front_9_par %>)<br />
    Back 9: <%= @course.back_9_yards %> yards (par <%= @course.back_9_par %>)<br />
    Last Played: <%= @course.scorecards.count > 0? @course.last_played : "Never"  %>
  </div>
  <div class="large-3 columns">
		<div class="gmaps4rails_map_single">
		  <%= gmaps(@gmaps_options) %>
		</div>
		<%= simple_form_for @course do |f| %>
		  <%= f.input :saddr, label: false, placeholder: "Get Directions" %>
	  <% end %>
  </div>
  <div class="large-8 columns">
    <%= link_to "Add Scores", new_scorecard_path(course: @course.id), class: "button radius" %>
    <table>
      <thead>
        <tr>
          <th>Hole</th>
          <th>Yards</th>
          <% if @course.course_type.name == "Full" %>
            <th>Red</th>
            <th>Blue</th>
          <% end %>
          <th>Par</th>
          <th>Avg</th>
          <th>Max</th>
          <th>Min</th>
          <th>1's</th>
          <th>A</th>
          <th>E</th>
          <th>B</th>
          <th>-</th>
          <th>+1</th>
          <th>+2</th>
          <th>>2</th>
        </tr>
      <tbody>
        <% @course.holes.each do |h| %>
        <tr>
          <td><%= h.hole_number %></td>
          <td><%= h.yards %></td>
          <% if @course.course_type.name == "Full" %>
            <td style="background-color: red; color: white"><%= h.red %></td>
            <td style="background-color: blue; color: white"><%= h.blue %></td>
          <% end %>          
          <td><%= h.par %></td>
          <td><%= h.average_score %></td>
          <td><%= h.max_score %></td>
          <td><%= h.min_score %></td>
          <td><%= h.hole_in_ones %></td>
          <td><%= h.albatrosses %></td>
          <td><%= h.eagles %></td>
          <td><%= h.birdies %></td>
          <td><%= h.evens %></td>
          <td><%= h.bogeys %></td>
          <td><%= h.double_bogeys %></td>
          <td><%= h.more_bogeys %></td>
        </tr>
        <% end %>
        <tr class="totals">
          <td class="totals">
          <td class="totals"><%= @course.total_yards %></td>
          <% if @course.course_type.name == "Full" %>
            <td class="totals" style="background-color: red; color: white"><%= @course.total_red %></td>
            <td class="totals" style="background-color: blue; color: white"><%= @course.total_blue %></td>
          <% end %>
          <td class="totals"><%= @course.par %></td>
          <% if @course.scorecards.count > 0 %>
          <td class="totals"><%= @course.course_average %></td>
          <td class="totals"></td>
          <td class="totals"></td>
          <td class="totals"><%= @course.hole_in_ones %></td>
          <td class="totals"><%= @course.albatrosses %></td>
          <td class="totals"><%= @course.eagles %></td>
          <td class="totals"><%= @course.birdies %></td>
          <td class="totals"><%= @course.evens %></td>
          <td class="totals"><%= @course.bogeys %></td>
          <td class="totals"><%= @course.double_bogeys %></td>
          <td class="totals"><%= @course.more_bogeys %></td>
          <% end %>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="large-4 columns">
    <br /><br />
    <% if @course.scorecards.count > 0 %>
    <h3>Top Player</h3>
      <%= image_tag("crown.png") %> <%= link_to @course.top_player.name, user_path(@course.top_player) %> (<%= @course.top_score %>)
    <h3>Recent Games</h3>
      <% @course.scorecards.limit(5).order("played_on DESC").each do |s| %>
        <%= link_to s.played_on, scorecard_path(s) %>
        <ul>
        <% s.user_scores.each do |u| %>
          <li><%= link_to u.user.name, user_path(u) %> - <%= link_to u.total, scorecard_path(s) %></li>
        <% end %>
        </ul>
      <% end %>
    <% end %>
    <%= link_to "View All Scores", course_all_path(@course) %>
  </div>
</div>