config/routes.rb
Vgscorecard::Application.routes.draw do
  devise_for :users

  root :to => "courses#index"
  match "/admin" => "admin/courses#index"
  
  resources :courses, only: [:index, :show] do 
    get "all"
  end
  
  resources :users, only: [:index, :show]
  
  resources :scorecards
  
  namespace :admin do 
    resources :courses
    resources :users
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  attr_accessible :first_name, :last_name, :role, :password, :email, :confirmed_at, :name, :password_confirmation
  
  has_many :scores, through: :user_scores
  has_many :user_scores, dependent: :destroy
  has_many :scorecards, through: :user_scores
  
  validates :name, :email, :password, presence: true
  
  def to_param
    "#{name}".parameterize
  end
  
  def favorite_course
    
  end
  
  def hole_in_ones
    self.scores.where("score = ?", 1).count
  end
  
  def albatrosses
    i = 0
    self.scores.each do |s|
      if s.score == s.hole.par-3
        i = i + 1
      end
    end
    i
  end
  
  def eagles
    i = 0
    self.scores.each do |s|
      if s.score == s.hole.par-2
        i = i + 1
      end
    end
    i
  end
  
  def birdies
    i = 0
    self.scores.each do |s|
      if s.score == s.hole.par-1
        i = i + 1
      end
    end
    i
  end
  
  def evens
    i = 0
    self.scores.each do |s|
      if s.score == s.hole.par
        i = i + 1
      end
    end
    i
  end
  
  def bogeys
    i = 0
    self.scores.each do |s|
      if s.score == s.hole.par+1
        i = i + 1
      end
    end
    i
  end
  
  def double_bogeys
    i = 0
    self.scores.each do |s|
      if s.score == s.hole.par+2
        i = i + 1
      end
    end
    i
  end
  
  def more_bogeys
    i = 0
    self.scores.each do |s|
      if s.score > s.hole.par+2
        i = i + 1
      end
    end
    i
  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authenticate_user!
  def index
    if current_user.role == 'admin'
      @users = User.all
    else
      redirect_to courses_path
    end
  end
  
  def show
    if current_user.role == 'admin'    
      @user = User.find(params[:id])
    else
      redirect_to courses_path
    end
  end
  
  def new
    if current_user.role == 'admin'    
      @user = User.new
    else 
      redirect_to courses_path
    end
  end
  
  def create
    @user = User.new(params[:user])
    
    if @user.save
      redirect_to admin_users_path, notice: "User successfully created."
    else
      render :new
    end
  end
  
  def edit
    if current_user.role == 'admin'
      @user = User.find(params[:id])
    else
      redirect_to courses_path
    end
  end
  
  def update
    
  end
  
  def destroy
    
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.where("role <> ?", "admin")
  end
  
  def show
    @user = User.where("name = ?", params[:id]).first
  end
end

app/views/admin/users/_form.html.erb
<h4>User Info</h4>
<div class="large-6 columns">
  <%= f.input :first_name %>
</div>
<div class="large-6 columns">
  <%= f.input :last_name %>
</div>
<div class="large-6 columns">
  <%= f.input :username %>
</div>
<div class="large-6 columns">
  <%= f.input :role %>
</div>

app/views/admin/users/edit.html.erb
<div class="row push-up">
	<div class="large-12 columns">
		<div class="bg pad">
			<%= simple_form_for [:admin, @user], html: { class: "large-8" } do |f| %>
				<%= render partial: 'form', locals: { f: f } %>
				<div class="large-12 columns"><%= f.button :submit, "Save" %></div>
			<% end %>
		</div>
	</div>
</div>

app/views/admin/users/index.html.erb
<div class="row">
  <div class="large-10 columns">
    <h1>Users</h1>
  </div>
  <div class="large-2 columns">
    <%= link_to "New User", new_admin_user_path, class: "radius button" %>
  </div>
  <div class="large-12 columns">
    <table>
      <thead>
      <tr>
        <td>Username</td>
        <td>Full Name</td>
        <td>Role</td>
        <td>Actions</td>
      </tr>
      </thead>
      <tbody>
        <% @users.each do |u| %>
          <tr>
            <td><%= link_to u.name, user_path(u) %></td>
            <td><%= u.first_name %> <%= u.last_name %></td>
            <td><%= u.role %></td>
            <td><%= link_to "Edit", edit_admin_user_path(u), class: "label" %> <%= link_to "Delete", nil, class: "label alert" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/users/new.html.erb
<div class="row push-up">
	<div class="large-12 columns">
		<div class="bg pad">
			<%= simple_form_for [:admin, @user], html: { class: "large-8" } do |f| %>
				<%= render partial: 'form', locals: { f: f } %>
				<div class="large-12 columns"><%= f.button :submit, "Create" %></div>
			<% end %>
		</div>
	</div>
</div>