config/routes.rb
Vgscorecard::Application.routes.draw do
  devise_for :users

  root :to => "courses#index"
  match "/admin" => "admin/courses#index"
  
  resources :courses, only: [:index, :show] do 
    get "all"
  end
  
  resources :users, only: [:index, :show]
  
  resources :scorecards
  
  namespace :admin do 
    resources :courses
    resources :users
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Vangolfers - Scorecards" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= stylesheet_link_tag "application", "http://code.jquery.com/ui/1.10.3/themes/smoothness/jquery-ui.css" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
   	<div class="contain-to-grid">
  	  <nav class="top-bar">
        <ul class="title-area">
          <li class="name">
  					<%= link_to "VG Scorecard", root_path, class: "logo" %>
  				</li>
  				<li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
        </ul>
  	    <section class="top-bar-section">
  	      <ul class="right">
  	        <li><%= link_to "Courses", courses_path(all: true) %>
  	        <li><%= link_to "Q&A", "http://www.vangolfers.com" %>
  	        <% if user_signed_in? %>
  	          <li><%= link_to "My Profile", user_path(current_user) %></li>
  	          <% if current_user.role == "admin" %>
  	            <li class="has-dropdown"><%= link_to "Admin", "#" %>
  	              <ul class="dropdown">
  	                <li><%= link_to "Courses", admin_courses_path %></li>
  	                <li><%= link_to "Users", admin_users_path %></li>
  	              </ul>  
  	            </li>
  	          <% end %>
  	          <li><%= link_to "Log out", destroy_user_session_path, :method => :delete %></li>
  	        <% else %>
  	          <li><%= link_to "Login", new_user_session_url %></li>
  	        <% end %>
  	      </ul>
  	    </section>
  	  </nav>
  	</div>
    <%= yield %>
    <%= javascript_include_tag "application" %>
    <%= yield :scripts %>
  </body>
</html>